
export default {
  PRIMARY: '#F25B5D',
  SECONDARY: '#F1F0F7',
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  TEXT_PRIMARY: '#FFFFFF',
  TEXT_SECONDAY: '#353130',
  TEXT_GRAY: '#B0B0B0',
  SCREEN_BACKGROUND: '#FAFAFA'
}